#27 analysed UC01 and UC03. created UC04. created full UC-diagram.
jakobkmar/E09-modellflug-logbuch pull request #32
Opened 2023-12-15 14:13 UTC by laurinVV

2023-12-17 10:28 UTC, Felix-Glieme requested changes
bis auf die 3 Glossary Änderungen habe ich nichts auszusetzen. Sehr gute Arbeit.

2023-12-17 10:28 UTC, Felix-Glieme commented on docs/requirements/use_case_01.inc.adoc
> +Der Akteur Admin administriert die Lösung.
Hier würde ich eher sowas schreiben wie:
- ein Admin ist der Verwalter des Gesamtsystems
- er pflegt dieses und kann Änderungen vornehmen

2023-12-17 10:28 UTC, Felix-Glieme commented on docs/requirements/use_case_01.inc.adoc
> +Der Akteur Pilot entsteht durch diesen Use-Case.
Auch hier würde ich eher sagen:
- ein Pilot ist der Benutzer des Systems und des Flugplatzes
- er kann Veränderungen an seinem Profil vornehmen, jedoch nicht am Gesamtsystem

2023-12-17 10:28 UTC, Felix-Glieme commented on docs/requirements/use_case_03.inc.adoc
> +Der Akteur Pilot kann nach dem Anmelden ein Protokoll anlegen.
Hier würde ich die gleiche Beschreibung wie zuvor einfügen. Das Glossary soll ja meiner Meinung nach die Rolle insgesamt beschreiben und nicht nur auf den jeweiligen Use-Case bezogen. Deshalb sollten sich die Beschreibungen gleichen.

2023-12-17 16:14 UTC, Julian-Tradien commented on docs/requirements/use_case_03.inc.adoc
> +. Der Use Case ist abgeschlossen.
Punkt am Ende bei allen oder bei keinem

2023-12-17 16:17 UTC, Julian-Tradien approved these changes

2023-12-17 20:34 UTC, nolan2019 approved these changes

2023-12-17 21:55 UTC, jakobkmar requested changes

2023-12-17 21:55 UTC, jakobkmar commented on .vscode/settings.json
bitte diese datei entfernen
ist eigentlich auch in der `.gitignore` schon drin, aber die branch von diesem PR scheint schon vorher abgezweigt worden zu sein

2023-12-18 13:38 UTC, Felix-Glieme approved these changes

2023-12-18 13:49 UTC, jakobkmar approved these changes

2023-12-18 13:51 UTC, merged