Create Table Statements
jakobkmar/E09-modellflug-logbuch pull request #72
Opened 2024-04-01 13:06 UTC by Coready

2024-04-05 13:24 UTC, laurinVV requested changes
bitte entsprechend https://github.com/jakobkmar/E09-modellflug-logbuch/pull/76 anpassen.

2024-04-15 11:48 UTC, Coready commented
@laurinVV 
review new changes

2024-04-15 15:52 UTC, laurinVV commented
ignore all previous and review this commit: https://github.com/jakobkmar/E09-modellflug-logbuch/pull/72/commits/61ff0455af41e453ff13eaf38514af58571f34fb

2024-04-24 15:18 UTC, jakobkmar approved these changes
Passt erstmal 👍 Anpassung wird im Laufe der Entwicklung noch kommen.

2024-04-24 15:19 UTC, merged